# Generated by Django 3.1.1 on 2020-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arnDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, null=True)),
                ('service', models.CharField(choices=[('vpn', 'vpn'), ('S3', 'S3')], max_length=20, null=True)),
                ('apis', models.CharField(max_length=100, null=True)),
                ('arn', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
